title: CreautureTime
description: Description goes here!
theme: just-the-docs

url: https://creature-time.github.io

aux_links:
  Template Repository: https://github.com/creature-time/website

plugins:
  - jekyll-gfm-admonitions